// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpofggfpaqgbaofvcavh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwb2ZnZ2ZwYXFnYmFvZnZjYXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjM2NzIsImV4cCI6MjA1NTc5OTY3Mn0.kJ1-oh3FEw-CbI3G6Ua0LO-x8fG01Ei-ctF349BlJlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);